import { Inter } from "next/font/google";
import "./globals.css";
import {Header, Footer} from "@/components/home";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white text-[#023535]">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
