/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/OdHux4ulgJS
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'
import { Tenor_Sans } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

tenor_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"
import { Card, CardContent } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export default function Home() {
  return (
    <div className="bg-white text-[#023535]">
      <header className="bg-[#008F8C] text-[#D8FFDB] py-8 px-4 md:px-6">
        <div className="container mx-auto max-w-5xl">
          <div className="grid gap-4 md:grid-cols-2 items-center">
            <div>
              <h1 className="text-4xl font-bold">Catalina Grajales</h1>
              <p className="text-lg text-[#D8FFDB]/80">Desarrolladora de Software</p>
            </div>
            <div className="flex justify-end">
              <img
                src="/placeholder.svg"
                alt="Catalina Grajales"
                className="rounded-full w-30 h-30"
                width="120"
                height="120"
                style={{ aspectRatio: "120/120", objectFit: "cover" }} />
            </div>
          </div>
        </div>
      </header>
      <main className="container mx-auto max-w-5xl py-12 px-4 md:px-6">
        <nav className="flex justify-center mb-8">
          <div className="flex gap-4 text-[#008F8C] font-medium">
            <Link href="#" className="hover:underline" prefetch={false}>
              Inicio
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Sobre Mí
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Proyectos
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Habilidades
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Contacto
            </Link>
          </div>
        </nav>
        <section>
          <h2 className="text-2xl font-bold mb-4">Introducción</h2>
          <p className="text-[#333333]">
            Soy una desarrolladora de software apasionada por la creación de soluciones tecnológicas innovadoras. Con
            más de 5 años de experiencia, he trabajado en una variedad de proyectos, desde aplicaciones web hasta
            sistemas de gestión empresarial. Mi enfoque se centra en escribir código limpio, eficiente y escalable,
            siempre buscando mejorar la experiencia del usuario.
          </p>
        </section>
        <section className="mt-12">
          <h2 className="text-2xl font-bold mb-4">Proyectos</h2>
          <Carousel className="w-full max-w-5xl">
            <CarouselContent>
              <CarouselItem>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                  <Card>
                    <CardContent>
                      <img
                        src="/placeholder.svg"
                        alt="Proyecto 1"
                        className="rounded-t-lg w-full h-48 object-cover"
                        width="300"
                        height="200"
                        style={{ aspectRatio: "300/200", objectFit: "cover" }} />
                      <div className="p-4">
                        <h3 className="text-xl font-bold mb-2">Proyecto 1</h3>
                        <p className="text-[#333333]">Descripción del Proyecto 1</p>
                        <Link
                          href="#"
                          className="inline-flex items-center mt-4 text-[#008F8C] hover:underline"
                          prefetch={false}>
                          Ver Detalles
                          <ArrowRightIcon className="ml-1 w-4 h-4" />
                        </Link>
                      </div>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardContent>
                      <img
                        src="/placeholder.svg"
                        alt="Proyecto 2"
                        className="rounded-t-lg w-full h-48 object-cover"
                        width="300"
                        height="200"
                        style={{ aspectRatio: "300/200", objectFit: "cover" }} />
                      <div className="p-4">
                        <h3 className="text-xl font-bold mb-2">Proyecto 2</h3>
                        <p className="text-[#333333]">Descripción del Proyecto 2</p>
                        <Link
                          href="#"
                          className="inline-flex items-center mt-4 text-[#008F8C] hover:underline"
                          prefetch={false}>
                          Ver Detalles
                          <ArrowRightIcon className="ml-1 w-4 h-4" />
                        </Link>
                      </div>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardContent>
                      <img
                        src="/placeholder.svg"
                        alt="Proyecto 3"
                        className="rounded-t-lg w-full h-48 object-cover"
                        width="300"
                        height="200"
                        style={{ aspectRatio: "300/200", objectFit: "cover" }} />
                      <div className="p-4">
                        <h3 className="text-xl font-bold mb-2">Proyecto 3</h3>
                        <p className="text-[#333333]">Descripción del Proyecto 3</p>
                        <Link
                          href="#"
                          className="inline-flex items-center mt-4 text-[#008F8C] hover:underline"
                          prefetch={false}>
                          Ver Detalles
                          <ArrowRightIcon className="ml-1 w-4 h-4" />
                        </Link>
                      </div>
                    </CardContent>
                  </Card>
                </div>
              </CarouselItem>
              <CarouselItem>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                  <Card>
                    <CardContent>
                      <img
                        src="/placeholder.svg"
                        alt="Proyecto 4"
                        className="rounded-t-lg w-full h-48 object-cover"
                        width="300"
                        height="200"
                        style={{ aspectRatio: "300/200", objectFit: "cover" }} />
                      <div className="p-4">
                        <h3 className="text-xl font-bold mb-2">Proyecto 4</h3>
                        <p className="text-[#333333]">Descripción del Proyecto 4</p>
                        <Link
                          href="#"
                          className="inline-flex items-center mt-4 text-[#008F8C] hover:underline"
                          prefetch={false}>
                          Ver Detalles
                          <ArrowRightIcon className="ml-1 w-4 h-4" />
                        </Link>
                      </div>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardContent>
                      <img
                        src="/placeholder.svg"
                        alt="Proyecto 5"
                        className="rounded-t-lg w-full h-48 object-cover"
                        width="300"
                        height="200"
                        style={{ aspectRatio: "300/200", objectFit: "cover" }} />
                      <div className="p-4">
                        <h3 className="text-xl font-bold mb-2">Proyecto 5</h3>
                        <p className="text-[#333333]">Descripción del Proyecto 5</p>
                        <Link
                          href="#"
                          className="inline-flex items-center mt-4 text-[#008F8C] hover:underline"
                          prefetch={false}>
                          Ver Detalles
                          <ArrowRightIcon className="ml-1 w-4 h-4" />
                        </Link>
                      </div>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardContent>
                      <img
                        src="/placeholder.svg"
                        alt="Proyecto 6"
                        className="rounded-t-lg w-full h-48 object-cover"
                        width="300"
                        height="200"
                        style={{ aspectRatio: "300/200", objectFit: "cover" }} />
                      <div className="p-4">
                        <h3 className="text-xl font-bold mb-2">Proyecto 6</h3>
                        <p className="text-[#333333]">Descripción del Proyecto 6</p>
                        <Link
                          href="#"
                          className="inline-flex items-center mt-4 text-[#008F8C] hover:underline"
                          prefetch={false}>
                          Ver Detalles
                          <ArrowRightIcon className="ml-1 w-4 h-4" />
                        </Link>
                      </div>
                    </CardContent>
                  </Card>
                </div>
              </CarouselItem>
              <CarouselItem>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                  <Card>
                    <CardContent>
                      <img
                        src="/placeholder.svg"
                        alt="Proyecto 7"
                        className="rounded-t-lg w-full h-48 object-cover"
                        width="300"
                        height="200"
                        style={{ aspectRatio: "300/200", objectFit: "cover" }} />
                      <div className="p-4">
                        <h3 className="text-xl font-bold mb-2">Proyecto 7</h3>
                        <p className="text-[#333333]">Descripción del Proyecto 7</p>
                        <Link
                          href="#"
                          className="inline-flex items-center mt-4 text-[#008F8C] hover:underline"
                          prefetch={false}>
                          Ver Detalles
                          <ArrowRightIcon className="ml-1 w-4 h-4" />
                        </Link>
                      </div>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardContent>
                      <img
                        src="/placeholder.svg"
                        alt="Proyecto 8"
                        className="rounded-t-lg w-full h-48 object-cover"
                        width="300"
                        height="200"
                        style={{ aspectRatio: "300/200", objectFit: "cover" }} />
                      <div className="p-4">
                        <h3 className="text-xl font-bold mb-2">Proyecto 8</h3>
                        <p className="text-[#333333]">Descripción del Proyecto 8</p>
                        <Link
                          href="#"
                          className="inline-flex items-center mt-4 text-[#008F8C] hover:underline"
                          prefetch={false}>
                          Ver Detalles
                          <ArrowRightIcon className="ml-1 w-4 h-4" />
                        </Link>
                      </div>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardContent>
                      <img
                        src="/placeholder.svg"
                        alt="Proyecto 9"
                        className="rounded-t-lg w-full h-48 object-cover"
                        width="300"
                        height="200"
                        style={{ aspectRatio: "300/200", objectFit: "cover" }} />
                      <div className="p-4">
                        <h3 className="text-xl font-bold mb-2">Proyecto 9</h3>
                        <p className="text-[#333333]">Descripción del Proyecto 9</p>
                        <Link
                          href="#"
                          className="inline-flex items-center mt-4 text-[#008F8C] hover:underline"
                          prefetch={false}>
                          Ver Detalles
                          <ArrowRightIcon className="ml-1 w-4 h-4" />
                        </Link>
                      </div>
                    </CardContent>
                  </Card>
                </div>
              </CarouselItem>
            </CarouselContent>
            <CarouselPrevious />
            <CarouselNext />
          </Carousel>
        </section>
        <section className="mt-12">
          <h2 className="text-2xl font-bold mb-4">Habilidades Técnicas</h2>
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
            <div className="bg-[#D8FFDB] rounded-lg p-4 text-center">
              <CodeIcon className="w-8 h-8 mb-2 text-[#008F8C]" />
              <p className="text-[#333333]">JavaScript</p>
            </div>
            <div className="bg-[#D8FFDB] rounded-lg p-4 text-center">
              <CodeIcon className="w-8 h-8 mb-2 text-[#008F8C]" />
              <p className="text-[#333333]">React</p>
            </div>
            <div className="bg-[#D8FFDB] rounded-lg p-4 text-center">
              <CodeIcon className="w-8 h-8 mb-2 text-[#008F8C]" />
              <p className="text-[#333333]">Node.js</p>
            </div>
            <div className="bg-[#D8FFDB] rounded-lg p-4 text-center">
              <CodeIcon className="w-8 h-8 mb-2 text-[#008F8C]" />
              <p className="text-[#333333]">MongoDB</p>
            </div>
            <div className="bg-[#D8FFDB] rounded-lg p-4 text-center">
              <CodeIcon className="w-8 h-8 mb-2 text-[#008F8C]" />
              <p className="text-[#333333]">SQL</p>
            </div>
            <div className="bg-[#D8FFDB] rounded-lg p-4 text-center">
              <CodeIcon className="w-8 h-8 mb-2 text-[#008F8C]" />
              <p className="text-[#333333]">Git</p>
            </div>
            <div className="bg-[#D8FFDB] rounded-lg p-4 text-center">
              <CodeIcon className="w-8 h-8 mb-2 text-[#008F8C]" />
              <p className="text-[#333333]">AWS</p>
            </div>
            <div className="bg-[#D8FFDB] rounded-lg p-4 text-center">
              <CodeIcon className="w-8 h-8 mb-2 text-[#008F8C]" />
              <p className="text-[#333333]">Docker</p>
            </div>
          </div>
        </section>
        <section className="mt-12">
          <h2 className="text-2xl font-bold mb-4">Referencias</h2>
          <Carousel className="w-full">
            <CarouselContent>
              <CarouselItem>
                <div className="grid grid-cols-2 gap-4">
                  <Card>
                    <CardContent>
                      <div className="flex items-center mb-4">
                        <Avatar>
                          <AvatarImage src="/placeholder-user.jpg" />
                          <AvatarFallback>JD</AvatarFallback>
                        </Avatar>
                        <div className="ml-4">
                          <h3 className="text-lg font-bold">John Doe</h3>
                          <p className="text-[#333333]">CEO, Acme Inc.</p>
                        </div>
                      </div>
                      <p className="text-[#333333]">
                        "Sofía es una desarrolladora excepcional. Su trabajo es\n siempre de alta calidad y entrega los
                        proyectos a tiempo.\n Recomiendo encarecidamente sus servicios."
                      </p>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardContent>
                      <div className="flex items-center mb-4">
                        <Avatar>
                          <AvatarImage src="/placeholder-user.jpg" />
                          <AvatarFallback>JL</AvatarFallback>
                        </Avatar>
                        <div className="ml-4">
                          <h3 className="text-lg font-bold">Jane Lowe</h3>
                          <p className="text-[#333333]">Gerente de Proyecto, Mega Corp.</p>
                        </div>
                      </div>
                      <p className="text-[#333333]">
                        "Trabajar con Sofía ha sido una experiencia increíble. Su\n conocimiento técnico y su capacidad
                        para resolver problemas\n han sido fundamentales para el éxito de nuestros proyectos."
                      </p>
                    </CardContent>
                  </Card>
                </div>
              </CarouselItem>
            </CarouselContent>
            <CarouselPrevious />
            <CarouselNext />
          </Carousel>
        </section>
        <section className="mt-12">
          <h2 className="text-2xl font-bold mb-4">Certificados y Educación</h2>
          <Carousel className="w-full">
            <CarouselContent>
              <CarouselItem>
                <div className="grid grid-cols-2 gap-4">
                  <Card>
                    <CardContent>
                      <div className="flex items-center mb-4">
                        <AwardIcon className="w-8 h-8 text-[#008F8C]" />
                        <div className="ml-4">
                          <h3 className="text-lg font-bold">Certificado en Desarrollo Web</h3>
                          <p className="text-[#333333]">Udemy, 2020</p>
                        </div>
                      </div>
                      <p className="text-[#333333]">
                        Certificado en desarrollo web full-stack, incluyendo tecnologías como HTML, CSS, JavaScript,
                        React, Node.js y más.
                      </p>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardContent>
                      <div className="flex items-center mb-4">
                        <AwardIcon className="w-8 h-8 text-[#008F8C]" />
                        <div className="ml-4">
                          <h3 className="text-lg font-bold">Licenciatura en Ingeniería Informática</h3>
                          <p className="text-[#333333]">Universidad Tecnológica, 2018</p>
                        </div>
                      </div>
                      <p className="text-[#333333]">
                        Licenciatura en Ingeniería Informática con especialización en Desarrollo de Software.
                      </p>
                    </CardContent>
                  </Card>
                </div>
              </CarouselItem>
            </CarouselContent>
            <CarouselPrevious />
            <CarouselNext />
          </Carousel>
        </section>
        <section className="mt-12">
          <h2 className="text-2xl font-bold mb-4">Contacto</h2>
          <form className="grid gap-4">
            <Input type="text" placeholder="Nombre" className="w-full" />
            <Input type="email" placeholder="Correo Electrónico" className="w-full" />
            <Textarea placeholder="Mensaje" className="w-full" />
            <Button type="submit" className="w-full bg-[#008F8C] text-[#D8FFDB] hover:bg-[#015958]">
              Enviar
            </Button>
          </form>
        </section>
        <section className="mt-12">
          <h2 className="text-2xl font-bold mb-4">Aprendizaje Actual</h2>
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
            <div className="bg-[#D8FFDB] rounded-lg p-4 text-center">
              <CodeIcon className="w-8 h-8 mb-2 text-[#008F8C]" />
              <p className="text-[#333333]">TypeScript</p>
            </div>
            <div className="bg-[#D8FFDB] rounded-lg p-4 text-center">
              <CodeIcon className="w-8 h-8 mb-2 text-[#008F8C]" />
              <p className="text-[#333333]">Next.js</p>
            </div>
            <div className="bg-[#D8FFDB] rounded-lg p-4 text-center">
              <CodeIcon className="w-8 h-8 mb-2 text-[#008F8C]" />
              <p className="text-[#333333]">GraphQL</p>
            </div>
            <div className="bg-[#D8FFDB] rounded-lg p-4 text-center">
              <CodeIcon className="w-8 h-8 mb-2 text-[#008F8C]" />
              <p className="text-[#333333]">Kubernetes</p>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-[#008F8C] text-[#D8FFDB] py-6 px-4 md:px-6">
        <div className="container mx-auto max-w-5xl flex justify-between items-center">
          <p className="text-sm">&copy; 2024 Catalina Grajales. Todos los derechos reservados.</p>
          <div className="flex gap-4">
            <Link href="#" className="hover:underline" prefetch={false}>
              Términos de Servicio
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Política de Privacidad
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}

function ArrowRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>)
  );
}


function CodeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>)
  );
}

function AwardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15.477 12.89 1.515 8.526a.5.5 0 0 1-.81.47l-3.58-2.687a1 1 0 0 0-1.197 0l-3.586 2.686a.5.5 0 0 1-.81-.469l1.514-8.526" />
      <circle cx="12" cy="8" r="6" />
    </svg>
  )
}